
- name: deploy.yml
  hosts: all
  become: yes
  vars:
    kerberos:
      realm: "{{ ansible_domain | upper }}"
      password: nimda
    ambari:
       url: http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.6.1.5
       password: nimda
    hdp:
      version: 2.6
      subversion: 2.6.4.0-91
      url: http://public-repo-1.hortonworks.com/HDP/centos7/2.x/updates/2.6.4.0
      preinstall: true
    hdp_utils:
      version: 1.1.0.22
      url: http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.22/repos/centos7
    cluster:
      name: sandbox
      ranger_password: admin123

  roles:
    - { role: 'jdk', tags: 'pre' }
    - { role: 'kerberos', tags: 'pre' }
    - { role: 'postgresql', tags: 'pre' }
    - { role: 'ambari', tags: 'pre' }
    - { role: 'hdp',  tags: 'main' }

