
- name: deploy.yml
  hosts: all
  vars:
    kerberos_realm: "{{ ansible_domain | upper }}"
    kerberos_password: passw0rd
    ambari_url: http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.6.1.5
    ambari_password: passw0rd
    hdp_version: 2.6.4.0-91
    hdp_url: http://public-repo-1.hortonworks.com/HDP/centos7/2.x/updates/2.6.4.0
    cluster_name: sandbox
    ranger_password: passw0rd

  roles:
    - { role: 'jdk', become: yes, tags: 'prepare' }
    - { role: 'kerberos', become: yes, tags: 'prepare' }
    - { role: 'postgresql', become: yes, tags: 'prepare' }
    - { role: 'ambari', become: yes, tags: 'prepare' }
    - { role: 'hdp',  become: yes, tags: 'install' }
    - { role: 'client', tags: 'test' }
