
- name: deploy.yml
  hosts: all
  become: yes
  vars:
    kerberos:
      realm: "{{ ansible_domain | upper }}"
      password: nimda
    ambari:
       url: http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.6.1.5
       password: nimda
  roles:
    - { role: 'jdk', tags: 'pre' }
    - { role: 'kerberos', tags: 'pre' }
    - { role: 'postgresql', tags: 'pre' }
    - { role: 'ambari', tags: 'pre' }
    - { role: 'hdp',  tags: 'main' }

