# the playbook expects following variables to be passed with --extra-vars
# username: Unix user to be created
# userkey: public key for SSH
# github_repo: github repository (relative path)
# centos_mirror: fqdn or @IP of CentOS mirror (optional)

- name: install.yml
  hosts: localhost
  become: true
  vars:
    # python -c 'import crypt; print crypt.crypt("password", "$1$SomeSalt$")'
    password: $1$SomeSalt$/jbIwfYCu0MxPBND2EtRH.

  tasks:
    - name: install basic packages
      yum:
        name: "{{ item }}"
      with_items:
        - sudo
        - nano
        - git

    - name: ensure that wheel group exist
      group:
        name: wheel

    - name: allow passwordless sudo for wheel group
      lineinfile:
        dest: /etc/sudoers
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: create working user {{ username }}
      user:
        name: "{{ username }}"
        password: "{{ client.password }}"
        group: users
        groups: wheel

    - name: add public key to user {{ username }}
      authorized_key:
        user: "{{ username }}"
        key: "{{ userkey }}"

    - name: clone the git repo github.com/{{ github_repo }}
      git:
        repo: https://github.com/{{ github_repo }}.git
        dest: /home/{{ username }}/deploy

    - name: update the repo owner 
      file:
        path: /home/{{ username }}/deploy
        owner: "{{ username }}"
        group: users

    - set_fact:
        local_epel: http://{{ centos_mirror }}/fedora/epel/$releasever/$basearch/
      when: centos_mirror is defined
      
    - name: Add Epel repo
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: "{{ local_epel |default('https://download.fedoraproject.org/pub/epel/$releasever/$basearch/') }}"
        gpgcheck: no

    - name: run the deploy playbook from /home/{{ username }}/deploy
      shell: ansible-playbook deploy.yml
      args:
        chdir: /home/{{ username }}/deploy
