# the playbook expects following variables to be passed with --extra-vars
# username: Unix user to be created
# password: password or public SSH key 
# github_repo: github repository (relative path)
# centos_mirror: fqdn or @IP of CentOS mirror (optional)

- hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: install basic packages
      yum:
        name: "{{ item }}"
      with_items:
        - sudo
        - nano
        - git

    - name: check for host rpm files
      find:
        path: /vagrant
        patterns: "*.rpm"
      ignore_errors: yes
      register: rpm_files

    - name: install rpm files
      yum:
        name: "{{ item.path }}"
      with_items: "{{ rpm_files.files }}"
      when: rpm_files.matched > 0

    - name: ensure that wheel group exist
      group:
        name: wheel

    - name: allow passwordless sudo for wheel group
      lineinfile:
        dest: /etc/sudoers
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: create user {{ username }}
      user:
        name: "{{ username }}"
        group: users
        groups: wheel

    - name: add public key to user {{ username }}
      authorized_key:
        user: "{{ username }}"
        key: "{{ password }}"
      when: password is match ("ssh-rsa .*")

    - name: update password for user {{ username }}
      user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
        update_password: always
      when: password is not match ("ssh-rsa .*")

    - name: allow PasswordAuthentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication '
        line: 'PasswordAuthentication yes'
      notify:
        - restart sshd
      when: password is not match ("ssh-rsa .*")

    - name: clone the git repo
      git:
        repo: https://github.com/{{ github_repo }}.git
        dest: /home/{{ username }}/git/{{ github_repo }}

    - name: update the owner
      file:
        path: /home/{{ username }}/git
        owner: "{{ username }}"
        group: users
        recurse: yes

    - set_fact:
        local_epel: http://{{ centos_mirror }}/fedora/epel/$releasever/$basearch/
      when: centos_mirror is defined
      
    - name: Add Epel repo
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: "{{ local_epel |default('https://download.fedoraproject.org/pub/epel/$releasever/$basearch/') }}"
        gpgcheck: no

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted
