# Destroy the cluster (tag kill)

- name: WARNING, all data will be lost. Type CTRL-C to stop the process
  wait_for:
    timeout: 10
  tags: kill

- name: stop the services
  uri:
    url: http://localhost:8080/api/v1/clusters/{{ hdp.cluster.name }}/services
    method: PUT
    user: admin
    password: "{{ hdp.cluster.password }}"
    body: '{"RequestInfo":{"context":"Stopping services"},"Body":{"ServiceInfo":{"state":"INSTALLED"}}}'
    force_basic_auth: yes
    status_code: 200,202
    body_format: raw
    headers:
      X-Requested-By: "ambari"
  ignore_errors: true
  tags: kill
  
- name: wait for services to stop
  wait_for:
    msg: "Checking {{ item.key }}"
    port: "{{ item.value }}"
    state: stopped
    host: "{{ inventory_hostname }}"
    timeout: 300
  with_dict: "{{ hdp.ports }}"
  tags: kill

- name: stop ambari
  service:
    name: "{{ item }}"
    state: stopped
  become: true
  with_items:
    - ambari-server
    - ambari-agent
  ignore_errors: true
  tags: kill

- name: drop Hive database
  postgresql_db:
    name: hive
    state: absent
  become: true
  become_user: postgres
  tags: kill

- name: drop Ranger database
  postgresql_db:
    name: ranger
    state: absent
  become: true
  become_user: postgres
  tags: kill

- name: drop Ambari database
  postgresql_db:
    name: ambari
    state: absent
  become: true
  become_user: postgres
  tags: kill

- name: cleanup /opt/ambari
  file:
    path: /opt/ambari/
    state: absent
  become: true
  tags: kill

# to be sure to cleanup Ambari's cache and data
- name: uninstall Ambari
  yum:
    name: "{{item }}"
    state: absent
  become: true
  with_items:
    - ambari-server
    - ambari-agent
  tags: kill

- name: cleanup keytabs
  file:
    path: /etc/security/keytabs/
    state: absent
  become: true
  tags: kill

- name: destroy Kerberos database
  shell: kdb5_util destroy -f
  args:
    removes: /var/kerberos/krb5kdc/principal
  become: true
  tags: kill

- name: cleanup hdfs data and solr
  file:
    path: "{{ item }}/"
    state: absent
  become: true
  with_items:
    - /hadoop
    - /opt/ambari_infra_solr/data
  tags: kill

- name: cleanup other data
  file:
    path: "/var/lib/{{ item }}/"
    state: absent
  become: true
  with_items:
    - ambari-server
    - ambari-agent
    - hadoop-hdfs
    - hadoop-mapreduce
    - hadoop-yarn
    - hive
    - hive2
    - ranger
    - zookeeper
  tags: kill

- name: cleanup logs
  file:
    path: "/var/log/{{ item }}/"
    state: absent
  become: true
  with_items:
    - ambari-server
    - ambari-agent
    - ranger
    - hbase
    - hadoop
    - hadoop-yarn
    - hadoop-mapreduce
    - hadoop-hdfs
    - hive2
    - ambari-infra-solr
    - zookeeper
    - hive-hcatalog
  tags: kill


- name: cleanup /tmp
  shell: rm -fr /tmp/Jetty* /tmp/krb* /tmp/ambari* /tmp/hadoop* /tmp/hsperfdata* /tmp/hbase* /tmp/hive* 
  args:
    warn: false
  become: true
  tags: kill

- name: remove users and groups
  user:
    name: "{{ item }}"
    state: absent
  become: true
  with_items:
    - infra-solr
    - tez
    - hcat
    - ranger
    - hive
    - hbase
    - mapred
    - hdfs
    - yarn
    - zookeeper
    - ambari-qa
  when: false
  tags: kill

- debug:
    msg: IT IS RECOMMENDED TO REBOOT SERVER NOW

