# Destroy the cluster (tag kill)

- name: WARNING, ALL DATA WILL BE LOST. TYPE CTRL-C TO STOP THE PLAYBOOK
  wait_for:
    timeout: 10
  tags: destroy

- name: stop the services
  uri:
    url: http://localhost:8080/api/v1/clusters/{{ cluster_name }}/services
    method: PUT
    user: admin
    password: "{{ ambari_password }}"
    body: '{"RequestInfo":{"context":"Stopping services"},"Body":{"ServiceInfo":{"state":"INSTALLED"}}}'
    force_basic_auth: yes
    status_code: 200,202
    body_format: raw
    headers:
      X-Requested-By: "ambari"
  ignore_errors: true
  tags: destroy
  
- name: wait for services to stop
  wait_for:
    msg: "Checking {{ item.key }}"
    port: "{{ item.value }}"
    state: stopped
    host: "{{ inventory_hostname }}"
    timeout: 300
  with_dict: "{{ ports }}"
  tags: destroy

- name: stop ambari
  service:
    name: "{{ item }}"
    state: stopped
  with_items:
    - ambari-server
    - ambari-agent
  ignore_errors: true
  tags: destroy

- name: drop Hive database
  postgresql_db:
    name: hive
    state: absent
  become_user: postgres
  tags: destroy

- name: drop Ranger database
  postgresql_db:
    name: ranger
    state: absent
  become_user: postgres
  tags: destroy

- name: drop Ambari database
  postgresql_db:
    name: ambari
    state: absent
  become_user: postgres
  tags: destroy

- name: cleanup /opt/ambari
  file:
    path: /opt/ambari/
    state: absent
  tags: destroy

- name: cleanup hdfs data and solr
  file:
    path: "{{ item }}/"
    state: absent
  with_items:
    - /hadoop
    - /opt/ambari_infra_solr/data
  tags: destroy

- name: cleanup other data
  file:
    path: "/var/lib/{{ item }}/"
    state: absent
  with_items:
    - ambari-server
    - ambari-agent
    - hadoop-hdfs
    - hadoop-mapreduce
    - hadoop-yarn
    - hive
    - hive2
    - ranger
    - zookeeper
  tags: destroy

- name: cleanup logs
  file:
    path: "/var/log/{{ item }}/"
    state: absent
  with_items:
    - ambari-server
    - ambari-agent
    - ranger
    - hbase
    - hadoop
    - hadoop-yarn
    - hadoop-mapreduce
    - hadoop-hdfs
    - hive2
    - ambari-infra-solr
    - zookeeper
    - hive-hcatalog
  tags: destroy

# uninstall Ambari to be sure to cleanup cache and data
- name: uninstall Ambari
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - ambari-server
    - ambari-agent
  tags: destroy

- name: cleanup keytabs
  file:
    path: /etc/security/keytabs/
    state: absent
  tags: destroy

- name: destroy Kerberos database
  shell: kdb5_util destroy -f
  args:
    removes: /var/kerberos/krb5kdc/principal
  tags: destroy

- name: cleanup /tmp
  shell: rm -fr /tmp/Jetty* /tmp/krb* /tmp/ambari* /tmp/hadoop* /tmp/hsperfdata* /tmp/hbase* /tmp/hive* 
  args:
    warn: false
  tags: destroy

- name: remove users and groups
  user:
    name: "{{ item }}"
    state: absent
  with_items:
    - infra-solr
    - tez
    - hcat
    - ranger
    - hive
    - hbase
    - mapred
    - hdfs
    - yarn
    - zookeeper
    - ambari-qa
  when: false
  tags: destroy

# reinstall Ambari from local files if exists
- name: check for rpm files in /vagrant
  find:
    path: /vagrant
    patterns: "*.rpm"
  ignore_errors: yes
  register: rpm_files
  tags: destroy

- name: install rpm files
  yum:
    name: "{{ rpm_files.files|map(attribute='path')|list }}"
  when: rpm_files.matched > 0 
  tags: destroy


- debug:
    msg: IT IS RECOMMENDED TO REBOOT SERVER NOW
  tags: destroy
