- name: install dependencies
  yum:
    name: "{{ dependencies }}"

# HDP Zookeper brings this useless dependency
- name: copy fake redhat-lsb
  copy:
    src: redhat-lsb-4.1-27.el7.centos.1.x86_64.rpm
    dest: /tmp

- name: install fake redhat-lsb
  yum:
    name: /tmp/redhat-lsb-4.1-27.el7.centos.1.x86_64.rpm

- name: check for local cache of HDP repo
  stat:
    path: /vagrant/cache
  register: hdp_cache

- name: install createrepo tool
  yum:
    name: createrepo
  when: hdp_cache.stat.exists

- name: run createrepo
  shell: createrepo /vagrant/cache
  args:
    creates: /vagrant/cache/repodata
  when: hdp_cache.stat.exists

- name: create local HDP repository
  yum_repository:
    name: HDP
    description: HDP-{{ hdp_version[0:3] }}
    baseurl: file:///vagrant/cache
    gpgcheck: no
  when: hdp_cache.stat.exists

- name: install all packages from cache
  yum:
    name: "{{ packages }}"
  when: hdp_cache.stat.exists

- name: create HDP repository
  yum_repository:
    name: HDP
    description: HDP-{{ hdp_version[0:3] }}
    baseurl: "{{ hdp_url }}"
    gpgcheck: no

- name: update yum.conf
  lineinfile:
    path: /etc/yum.conf
    regexp: '^keepcache=*'
    line: "keepcache=1"
  when: not hdp_cache.stat.exists

- name: refresh yum
  yum:
    list: available

- name: pre-install HDP packages
  yum:
    name: "{{ packages }}"

- name: download definition file for HDP-{{ hdp_version }}
  get_url:
    url: "{{ hdp_url }}/HDP-{{ hdp_version }}.xml"
    dest: /opt/HDP.xml

- name: prepare API payload
  set_fact:
    api_create_version:
      VersionDefinition:
        version_url: "file:/opt/HDP.xml"

- name: create the version HDP-{{ hdp_version }}
  uri:
    url: http://localhost:8080/api/v1/version_definitions
    method: POST
    user: admin
    password: "{{ ambari_password }}"
    body: "{{ api_create_version | to_json }}"
    status_code: 201
    force_basic_auth: yes
    body_format: raw
    headers:
      X-Requested-By: "ambari"



