# HDP Zookeper brings this useless dependency
- name: copy fake redhat-lsb
  copy:
    src: redhat-lsb-4.1-27.el7.centos.1.x86_64.rpm
    dest: /tmp

- name: install fake redhat-lsb
  yum:
    name: /tmp/redhat-lsb-4.1-27.el7.centos.1.x86_64.rpm

- name: install HDP repo
  yum_repository:
    name: HDP
    description: HDP-{{ hdp_version }}
    baseurl: "{{ hdp_url }}"
    gpgcheck: no

- name: pre-install HDP packages to speedup cluster deployment
  yum:
    name: "{{ packages }}"
  when: hdp_preinstall is defined and hdp_preinstall

- name: refresh yum
  yum:
    list: available

- name: download definition file for HDP-{{ hdp_version }}
  get_url:
    url: "{{ hdp_url }}/HDP-{{ hdp_version }}.xml"
    dest: /opt/HDP.xml

- name: prepare API payload
  set_fact:
    api_create_version:
      VersionDefinition:
        version_url: "file:/opt/HDP.xml"

- name: create the version HDP-{{ hdp_version }}
  uri:
    url: http://localhost:8080/api/v1/version_definitions
    method: POST
    user: admin
    password: "{{ ambari_password }}"
    body: "{{ api_create_version | to_json }}"
    status_code: 201
    force_basic_auth: yes
    body_format: raw
    headers:
      X-Requested-By: "ambari"



