- name: create environment file for hdp
  template:
    src: env-HDP.j2
    dest: /home/{{ ansible_ssh_user }}/env-HDP.sh

- name: update .bash_profile
  lineinfile:
    path: /home/{{ ansible_ssh_user }}/.bash_profile
    line: ". env-HDP.sh"



