- name: create environment file for hdp
  template:
    src: env-HDP.j2
    dest: /home/{{ ansible_ssh_user }}/env-HDP.sh

- name: update .bashrc
  lineinfile:
    path: /home/{{ ansible_ssh_user }}/.bashrc
    line: ". env-HDP.sh"



